spring:
  application:
    name: gateway-server

  # Se añaden las configuraciones de kubernetes
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
      loadbalancer:
        mode: service
      config:
        enabled: true
      reload:
        enabled: true
        monitoring-config-maps: true
        strategy: refresh
        mode: event

    #Se añade la resolucion de paths basados en nombres de servicios registrados en kubernetes
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service-s
          predicates:
            - Path=/store/**
        - id: item-service
          uri: lb://item-service-s
          predicates:
            - Path=/goods/**
        - id: authorization-server
          uri: lb://authorization-server-s
          predicates:
            - Path=/app/**

  # Se añade la configuracion de conexion hacia el servicio de autorizacion - keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.localhost.nip.io/realms/udemy-realm-cloud
          jwk-set-uri: http://keycloak:8080/realms/udemy-realm-cloud/protocol/openid-connect/certs

logging:
  level:
    org.keycloak: debug
    root: debug

server:
  port: 8090